set_level:
  fields:
    level:
      required: true
      selector:
        number:
          min: 0
          max: 1000
          unit_of_measurement: kg
          mode: box
    entry_id:
      required: true
      selector:
        config_entry:
          integration: pellet_tracker
    calibrate:
      selector:
        boolean:
